import { textWidth, wrapText, buildPdf } from '@/lib/pdf'
import { GUIDE_SECTIONS, GUIDE_HIGHLIGHTS, GUIDE_FILENAME } from '@/lib/guideContent'

// Blob.text() is available in jsdom, so the generated bytes can be inspected
// directly rather than trusting the layout maths.

/**
 * Reads a Blob as bytes.
 *
 * jsdom's Blob has no .text(), and more importantly xref offsets are byte
 * offsets, not JavaScript string indices. The guide contains multi-byte UTF-8
 * (the middle-dot separator in the footer), so a string index would not line up
 * with a byte offset. Each byte is therefore mapped to one character, keeping
 * index and offset identical.
 */
function readBlobBytes(blob: Blob): Promise<string> {
  return new Promise((resolve, reject) => {
    const reader = new FileReader()
    reader.onload = () => {
      const buffer = reader.result as ArrayBuffer
      const bytes = new Uint8Array(buffer)
      let out = ''
      for (let i = 0; i < bytes.length; i++) out += String.fromCharCode(bytes[i])
      resolve(out)
    }
    reader.onerror = () => reject(reader.error)
    reader.readAsArrayBuffer(blob)
  })
}

/** Writes the generated PDF to disk so it can be opened in a real reader. */
async function writeToFile(blob: Blob, filename: string) {
  const bytes = await readBlobBytes(blob)
  const { writeFileSync } = await import('fs')
  // Re-interpret the latin1 string as raw bytes.
  const buf = Buffer.from(bytes, 'latin1')
  writeFileSync(filename, buf)
  return buf.length
}

describe('textWidth', () => {
  it('measures a string proportionally to its font size', () => {
    expect(textWidth('Hello', 10)).toBeCloseTo(textWidth('Hello', 20) / 2, 5)
  })

  it('gives a space a positive width', () => {
    expect(textWidth(' ', 10)).toBeGreaterThan(0)
  })

  it('measures wider for bold than regular', () => {
    expect(textWidth('Total revenue', 10, true)).toBeGreaterThan(textWidth('Total revenue', 10))
  })

  it('treats unknown glyphs as a wide letter rather than zero', () => {
    // A curly quote must not collapse the measured width to nothing.
    expect(textWidth('\u2019', 10)).toBeGreaterThan(textWidth('i', 10))
  })

  it('returns zero for an empty string', () => {
    expect(textWidth('', 10)).toBe(0)
  })
})

describe('wrapText', () => {
  it('keeps short text on one line', () => {
    expect(wrapText('Short line', 400, 11)).toEqual(['Short line'])
  })

  it('breaks long text across lines', () => {
    const long = 'word '.repeat(80).trim()
    const lines = wrapText(long, 200, 11)
    expect(lines.length).toBeGreaterThan(1)
    lines.forEach((l) => expect(textWidth(l, 11)).toBeLessThanOrEqual(200 + 0.001))
  })

  it('never loses or invents words when wrapping', () => {
    const long = 'alpha beta gamma delta epsilon zeta eta theta iota kappa lambda mu nu xi'
    const lines = wrapText(long, 120, 10)
    expect(lines.join(' ').split(/\s+/)).toEqual(long.split(/\s+/))
  })

  it('returns a single empty line for empty input', () => {
    expect(wrapText('', 200, 11)).toEqual([''])
  })

  it('keeps a single word intact even when it is wider than the box', () => {
    // Long unbreakable tokens must still render rather than loop forever.
    expect(wrapText('supercalifragilistic', 10, 11)).toEqual(['supercalifragilistic'])
  })

  it('collapses runs of whitespace', () => {
    expect(wrapText('a   b', 400, 11)).toEqual(['a b'])
  })
})

describe('buildPdf', () => {
  const sections = [
    { heading: 'Short', body: ['One line of body text.'] },
    {
      heading: 'Long',
      body: ['word '.repeat(400).trim()],
      bullets: ['A bullet that is quite long and will need wrapping across a line or two.'],
    },
  ]

  it('produces a Blob with the PDF media type', () => {
    const blob = buildPdf({ title: 'Guide', sections: [{ heading: 'A', body: ['B'] }] })
    expect(blob.type).toBe('application/pdf')
  })

  it('emits a valid PDF header and trailer', async () => {
    const blob = buildPdf({ title: 'Guide', sections })
    const text = await readBlobBytes(blob)
    expect(text.startsWith('%PDF-1.4')).toBe(true)
    expect(text.trimEnd().endsWith('%%EOF')).toBe(true)
    expect(text).toContain('/Type /Catalog')
    expect(text).toContain('/BaseFont /Helvetica')
  })

  it('writes a cross-reference table whose offsets point at real objects', async () => {
    const blob = buildPdf({ title: 'Guide', sections })
    const text = await readBlobBytes(blob)

    const startxrefMatch = /startxref\s+(\d+)/.exec(text)
    expect(startxrefMatch).not.toBeNull()
    const xrefStart = Number(startxrefMatch![1])

    // The xref keyword must sit exactly where startxref claims it does.
    expect(text.slice(xrefStart, xrefStart + 4)).toBe('xref')

    // Every in-use offset must land on "N 0 obj".
    const entryRe = /^(\d{10}) 00000 n $/gm
    let match: RegExpExecArray | null
    let checked = 0
    while ((match = entryRe.exec(text)) !== null) {
      const offset = Number(match[1])
      expect(text.slice(offset, offset + 3)).toMatch(/^\d+ 0/)
      checked++
    }
    expect(checked).toBeGreaterThan(0)
  })

  it('escapes parentheses so string literals cannot break the content stream', async () => {
    const blob = buildPdf({
      title: 'Guide',
      sections: [{ heading: 'Costs (net)', body: ['A (parenthetical) note.'] }],
    })
    const text = await readBlobBytes(blob)
    // Escaped as \( and \), so the stream stays syntactically valid.
    expect(text).toContain('\\(net\\)')
    expect(text).toContain('\\(parenthetical\\)')
  })

  it('paginates a long document across multiple pages', async () => {
    // Enough text to overflow an A4 page many times over.
    const longSections = Array.from({ length: 8 }, (_, i) => ({
      heading: `Section ${i + 1}`,
      body: ['word '.repeat(200).trim()],
      bullets: ['bullet '.repeat(60).trim()],
    }))
    const blob = buildPdf({ title: 'Guide', sections: longSections })
    const text = await readBlobBytes(blob)
    const pageCount = Number(/\/Type \/Pages \/Kids \[.*?\] \/Count (\d+)/.exec(text)![1])
    expect(pageCount).toBeGreaterThan(1)

    // One content stream per declared page.
    const contentStreams = (text.match(/\/Length \d+ >>\nstream/g) || []).length
    expect(contentStreams).toBe(pageCount)

    // Page numbers run 1..N and each page carries its own footer.
    for (let i = 1; i <= pageCount; i++) {
      expect(text).toContain(`Page ${i} of ${pageCount}`)
    }
  })

  it('includes every section heading in the output', async () => {
    const blob = buildPdf({ title: 'Guide', sections: GUIDE_SECTIONS })
    const text = await readBlobBytes(blob)
    GUIDE_SECTIONS.forEach((s) => {
      expect(text).toContain(s.heading.split(' ').slice(0, 3).join(' '))
    })
  })

  it('generates the real guide as a valid multi-page PDF', async () => {
    const blob = buildPdf({
      title: 'How Business Bot GH works',
      subtitle: 'A practical guide',
      sections: GUIDE_SECTIONS,
    })
    const bytes = await readBlobBytes(blob)

    expect(bytes.startsWith('%PDF-1.4')).toBe(true)
    expect(bytes.trimEnd().endsWith('%%EOF')).toBe(true)

    const pageCount = Number(/\/Type \/Pages \/Kids \[.*?\] \/Count (\d+)/.exec(bytes)![1])
    expect(pageCount).toBeGreaterThan(1)
    expect((bytes.match(/\/Length \d+ >>\nstream/g) || []).length).toBe(pageCount)

    // The xref offsets must be byte-accurate or no reader will open the file.
    const xrefStart = Number(/startxref\s+(\d+)/.exec(bytes)![1])
    expect(bytes.slice(xrefStart, xrefStart + 4)).toBe('xref')

    const entryRe = /^(\d{10}) 00000 n $/gm
    let match: RegExpExecArray | null
    let checked = 0
    while ((match = entryRe.exec(bytes)) !== null) {
      // Two-digit object numbers need a longer slice than single-digit ones.
      expect(bytes.slice(Number(match[1]), Number(match[1]) + 9)).toMatch(/^\d+ 0 obj/)
      checked++
    }
    expect(checked).toBeGreaterThan(0)

    // Every declared stream length must match the bytes actually written.
    const streamRe = /<< \/Length (\d+) >>\nstream\n([\s\S]*?)\nendstream/g
    let stream: RegExpExecArray | null
    let streams = 0
    while ((stream = streamRe.exec(bytes)) !== null) {
      expect(stream[2].length).toBe(Number(stream[1]))
      streams++
    }
    expect(streams).toBe(pageCount)
  })

  it('writes a file a real PDF reader can open', async () => {
    const blob = buildPdf({
      title: 'How Business Bot GH works',
      subtitle: 'A practical guide',
      sections: GUIDE_SECTIONS,
    })
    await writeToFile(blob, '/tmp/guide-verification.pdf')
  })

  it('handles a document with no sections without throwing', () => {
    expect(() => buildPdf({ title: 'Empty', sections: [] })).not.toThrow()
  })
})

describe('guide content', () => {
  it('has nine sections, each with a heading and body', () => {
    expect(GUIDE_SECTIONS).toHaveLength(9)
    GUIDE_SECTIONS.forEach((s) => {
      expect(s.heading.length).toBeGreaterThan(0)
      expect(s.body.length).toBeGreaterThan(0)
    })
  })

  it('gives every section unique, ordered headings', () => {
    const headings = GUIDE_SECTIONS.map((s) => s.heading)
    expect(new Set(headings).size).toBe(headings.length)
    headings.forEach((h, i) => expect(h.startsWith(`${i + 1}.`)).toBe(true))
  })

  it('explains that deleting a sale restores stock', () => {
    const deleteSection = GUIDE_SECTIONS.find((s) =>
      s.heading.toLowerCase().includes('deleting')
    )!
    expect(deleteSection).toBeDefined()
    const allText = [...deleteSection.body, ...(deleteSection.bullets || [])].join(' ').toLowerCase()
    expect(allText).toContain('returned to stock')
  })

  it('surfaces the stock-restoration behaviour in the on-screen highlights', () => {
    const titles = GUIDE_HIGHLIGHTS.map((h) => h.title.toLowerCase())
    expect(titles.some((t) => t.includes('deleting') && t.includes('stock'))).toBe(true)
  })

  it('has highlights with both a title and a body', () => {
    expect(GUIDE_HIGHLIGHTS.length).toBeGreaterThan(0)
    GUIDE_HIGHLIGHTS.forEach((h) => {
      expect(h.title.length).toBeGreaterThan(0)
      expect(h.body.length).toBeGreaterThan(0)
    })
  })

  it('uses a .pdf filename', () => {
    expect(GUIDE_FILENAME.endsWith('.pdf')).toBe(true)
  })
})