/**
 * SMS contract tests.
 *
 * These pin the frontend to the backend's message format. The expected string
 * was generated by running the real
 * `RecieptReportGenerator.build_analytics_message()` template in Python with
 * the same inputs, so drift in either direction fails the suite.
 */
import {
  smsSegments,
  smsCostGhs,
  reportWindow,
  reportSchedule,
  formatReportStart,
  formatReportEnd,
  formatSmsAmount,
  formatSmsCount,
  buildReportSms,
  deriveReminderDelivery,
  reminderDeliveryMeta,
  REPORT_SCHEDULES,
  defaultDebtDueDate,
  outstandingBalance,
} from '@/lib/sms'
import { aggregateProductPerformance } from '@/lib/utils'

describe('smsSegments', () => {
  it('counts a short message as one part', () => {
    expect(smsSegments('short')).toBe(1)
  })

  it('allows exactly 160 characters in a single part', () => {
    expect(smsSegments('a'.repeat(160))).toBe(1)
  })

  it('splits past 160 using the 153-character multi-part size', () => {
    expect(smsSegments('a'.repeat(161))).toBe(2)
    expect(smsSegments('a'.repeat(306))).toBe(2)
    expect(smsSegments('a'.repeat(307))).toBe(3)
  })

  it('treats an empty message as one part rather than zero', () => {
    expect(smsSegments('')).toBe(1)
  })
})

describe('smsCostGhs', () => {
  it('charges per segment, not per character', () => {
    expect(smsCostGhs(1)).toBe(0.01)
    expect(smsCostGhs(2)).toBe(0.02)
    expect(smsCostGhs(3)).toBe(0.03)
  })
})

describe('REPORT_SCHEDULES', () => {
  it('covers daily, weekly and monthly', () => {
    expect(REPORT_SCHEDULES.map((s) => s.kind)).toEqual(['daily', 'weekly', 'monthly'])
  })

  it('uses the exact titles the backend passes to the generator', () => {
    // Verbatim from process_report_data() calls in src/tasks/jobs.py
    expect(reportSchedule('daily').smsTitle).toBe('Daily Sales Summary')
    expect(reportSchedule('weekly').smsTitle).toBe('Weekly Performance Overview')
    expect(reportSchedule('monthly').smsTitle).toBe('Monthly Revenue Report')
  })

  it('schedules every report for 19:00, matching the CronTriggers', () => {
    REPORT_SCHEDULES.forEach((s) => expect(s.sendAtUtc).toBe('19:00'))
  })
})

describe('reportWindow', () => {
  const now = new Date('2026-10-03T12:00:00Z')

  it('daily covers today only', () => {
    expect(reportWindow('daily', now)).toEqual({ start: '2026-10-03', end: '2026-10-03' })
  })

  it('weekly covers the last seven days up to today', () => {
    expect(reportWindow('weekly', now)).toEqual({ start: '2026-09-26', end: '2026-10-03' })
  })

  it('monthly starts on the 1st, matching the backend rewind', () => {
    expect(reportWindow('monthly', now)).toEqual({ start: '2026-10-01', end: '2026-10-03' })
  })

  it('monthly is correct at the very start of a month', () => {
    const first = new Date('2026-10-01T00:30:00Z')
    expect(reportWindow('monthly', first)).toEqual({ start: '2026-10-01', end: '2026-10-01' })
  })
})

describe('report date formatting', () => {
  it('formats the start as Python %b %d with a zero-padded day', () => {
    expect(formatReportStart('2026-10-03')).toBe('Oct 03')
    expect(formatReportStart('2026-01-09')).toBe('Jan 09')
  })

  it('formats the end with the year appended', () => {
    expect(formatReportEnd('2026-10-03')).toBe('Oct 03, 2026')
  })

  it('handles month boundaries', () => {
    expect(formatReportStart('2026-12-25')).toBe('Dec 25')
    expect(formatReportEnd('2027-01-02')).toBe('Jan 02, 2027')
  })

  it('returns the raw input when the date cannot be parsed', () => {
    expect(formatReportStart('')).toBe('')
    expect(formatReportEnd('not-a-date')).toBe('not-a-date')
  })
})

describe('formatSmsAmount', () => {
  it('matches Python :,.2f for thousands separators', () => {
    expect(formatSmsAmount(48250.5)).toBe('48,250.50')
    expect(formatSmsAmount(12000.25)).toBe('12,000.25')
  })

  it('always shows two decimals', () => {
    expect(formatSmsAmount(0)).toBe('0.00')
    expect(formatSmsAmount(1000)).toBe('1,000.00')
  })

  it('coerces null and NaN to 0.00, as the backend would', () => {
    expect(formatSmsAmount(null)).toBe('0.00')
    expect(formatSmsAmount(undefined)).toBe('0.00')
    expect(formatSmsAmount(NaN)).toBe('0.00')
  })
})

describe('formatSmsCount', () => {
  it('renders whole numbers without a decimal tail', () => {
    expect(formatSmsCount(37)).toBe('37')
    expect(formatSmsCount(0)).toBe('0')
  })

  it('does not append .0 to a float that is really a count', () => {
    expect(formatSmsCount(37.0)).toBe('37')
  })

  it('falls back to zero for missing values', () => {
    expect(formatSmsCount(null)).toBe('0')
    expect(formatSmsCount(undefined)).toBe('0')
  })
})

// ── The message itself ──────────────────────────────────────────────────────

describe('buildReportSms', () => {
  const summary = {
    total_revenue: 48250.5,
    total_profit: 12000.25,
    total_sales: 37,
    sold_quantity: 91,
    cash_total: 20,
    momo_total: 15,
    card_total: 2,
    best_selling_product: '\u4e2d\u6708',
  }

  // Generated by running the real Python template with these inputs.
  const EXPECTED = [
    'AUTOMATED REPORT',
    'Daily Sales Summary | Oct 03 - Oct 03, 2026',
    '',
    'Total Revenue: GHS 48,250.50',
    'Total Profit: GHS 12,000.25',
    'Total Orders: 37',
    'Units Sold: 91',
    '',
    'Payment breakdown',
    'Cash: 20',
    'Mobile money: 15',
    'Card: 2',
    '',
    'Best selling product: \u4e2d\u6708',
    '',
    'This is an automated report from your Sales Tracker.',
  ].join('\n')

  it('reproduces the backend message byte for byte', () => {
    const sms = buildReportSms({
      summary,
      start: '2026-10-03',
      end: '2026-10-03',
      title: 'Daily Sales Summary',
    })
    expect(sms).toBe(EXPECTED)
    // Python len() counts code points, same as JS for this content.
    expect(sms.length).toBe(283)
  })

  it('falls back to N/A when there is no best-selling product', () => {
    const sms = buildReportSms({
      summary: { ...summary, best_selling_product: null },
      start: '2026-10-03',
      end: '2026-10-03',
      title: 'Monthly Revenue Report',
    })
    expect(sms).toContain('Best selling product: N/A')
  })

  it('uses the supplied title and window', () => {
    const sms = buildReportSms({
      summary,
      start: '2026-10-01',
      end: '2026-10-03',
      title: 'Monthly Revenue Report',
    })
    expect(sms).toContain('Monthly Revenue Report | Oct 01 - Oct 03, 2026')
  })

  it('renders a zeroed summary without NaN leaking in', () => {
    const sms = buildReportSms({
      summary: {},
      start: '2026-10-03',
      end: '2026-10-03',
      title: 'Daily Sales Summary',
    })
    expect(sms).toContain('Total Revenue: GHS 0.00')
    expect(sms).toContain('Total Orders: 0')
    expect(sms).not.toContain('NaN')
  })
})

// ── Reminder delivery ───────────────────────────────────────────────────────

describe('deriveReminderDelivery', () => {
  const now = new Date('2026-10-03T12:00:00Z')

  it('treats a stamped sent_at as delivered', () => {
    expect(deriveReminderDelivery({ sent_at: '2026-10-02T09:00:00Z' }, {}, now)).toBe('sent')
  })

  it('marks a future reminder as scheduled', () => {
    expect(deriveReminderDelivery({ date: '2026-10-10', is_active: true }, {}, now)).toBe('scheduled')
  })

  it('marks a past active reminder with no send as due', () => {
    expect(deriveReminderDelivery({ date: '2026-10-01', is_active: true }, {}, now)).toBe('due')
  })

  it('treats a reminder dated today as due, not scheduled', () => {
    expect(deriveReminderDelivery({ date: '2026-10-03', is_active: true }, {}, now)).toBe('due')
  })

  it('honours an explicit paused flag', () => {
    expect(deriveReminderDelivery({ date: '2026-10-01', is_active: false }, {}, now)).toBe('paused')
  })

  it('marks the reminder settled once the debt is paid off', () => {
    expect(
      deriveReminderDelivery({ date: '2026-10-10', is_active: true }, { debtSettled: true }, now)
    ).toBe('settled')
  })

  it('prefers a real backend status when one is exposed', () => {
    expect(deriveReminderDelivery({ date: '2026-10-10' }, { status: 'failed' }, now)).toBe('failed')
    expect(deriveReminderDelivery({ date: '2026-10-10' }, { status: 'sending' }, now)).toBe('sending')
    expect(deriveReminderDelivery({ date: '2026-10-10' }, { status: 'sent' }, now)).toBe('sent')
  })

  it('falls back to scheduled for an unparseable date', () => {
    expect(deriveReminderDelivery({ date: '' }, {}, now)).toBe('scheduled')
  })
})

describe('reminderDeliveryMeta', () => {
  it('has a label and description for every state', () => {
    const states = ['scheduled', 'due', 'sending', 'sent', 'failed', 'paused', 'settled'] as const
    states.forEach((s) => {
      const meta = reminderDeliveryMeta(s)
      expect(meta.label).toBeTruthy()
      expect(meta.description).toBeTruthy()
      expect(meta.tone).toBeTruthy()
    })
  })
})

describe('aggregateProductPerformance', () => {
  const sale = (items: any[]) => ({ sale_id: 1, sales_items: items })

  it('ranks products by units sold, highest first', () => {
    const rows = aggregateProductPerformance([
      sale([
        { product_id: 1, product_name: 'Rice', quantity: 3, subtotal: 30, profit: 6 },
        { product_id: 2, product_name: 'Beans', quantity: 10, subtotal: 100, profit: 20 },
      ]),
    ])
    expect(rows[0].name).toBe('Beans')
    expect(rows[0].quantity).toBe(10)
    expect(rows[1].name).toBe('Rice')
  })

  it('sums the same product across separate sales', () => {
    const rows = aggregateProductPerformance([
      sale([{ product_id: 1, product_name: 'Rice', quantity: 2, subtotal: 20, profit: 4 }]),
      sale([{ product_id: 1, product_name: 'Rice', quantity: 5, subtotal: 50, profit: 10 }]),
    ])
    expect(rows).toHaveLength(1)
    expect(rows[0].quantity).toBe(7)
    expect(rows[0].revenue).toBe(70)
    expect(rows[0].profit).toBe(14)
  })

  it('derives revenue from unit_price when subtotal is absent', () => {
    const rows = aggregateProductPerformance([
      sale([{ product_id: 1, product_name: 'Rice', quantity: 4, unit_price: 12.5 }]),
    ])
    expect(rows[0].revenue).toBe(50)
  })

  it('computes each product share of total units', () => {
    const rows = aggregateProductPerformance([
      sale([
        { product_id: 1, product_name: 'Rice', quantity: 3, subtotal: 30 },
        { product_id: 2, product_name: 'Beans', quantity: 1, subtotal: 10 },
      ]),
    ])
    expect(rows[0].share).toBe(75)
    expect(rows[1].share).toBe(25)
  })

  it('falls back to the catalogue when a line item has no name', () => {
    const names = new Map([[7, 'Tomatoes']])
    const rows = aggregateProductPerformance(
      [sale([{ product_id: 7, quantity: 2, subtotal: 20 }])],
      names
    )
    expect(rows[0].name).toBe('Tomatoes')
  })

  it('uses a placeholder when no name is available anywhere', () => {
    const rows = aggregateProductPerformance([sale([{ product_id: 7, quantity: 2, subtotal: 20 }])])
    expect(rows[0].name).toBe('Product #7')
  })

  it('upgrades a placeholder name when a later row carries the real one', () => {
    const rows = aggregateProductPerformance([
      sale([{ product_id: 7, quantity: 1, subtotal: 10 }]),
      sale([{ product_id: 7, quantity: 1, subtotal: 10, product_name: 'Tomatoes' }]),
    ])
    expect(rows[0].name).toBe('Tomatoes')
    expect(rows[0].quantity).toBe(2)
  })

  it('ignores sales with no line items', () => {
    expect(aggregateProductPerformance([{ sale_id: 2, sales_items: [] }])).toEqual([])
    expect(aggregateProductPerformance([{ sale_id: 3 }])).toEqual([])
  })

  it('breaks a quantity tie on revenue', () => {
    const rows = aggregateProductPerformance([
      sale([
        { product_id: 1, product_name: 'A', quantity: 5, subtotal: 10 },
        { product_id: 2, product_name: 'B', quantity: 5, subtotal: 90 },
      ]),
    ])
    expect(rows[0].name).toBe('B')
  })

  it('handles an empty input without throwing', () => {
    expect(aggregateProductPerformance([])).toEqual([])
  })
})

describe('SaleEditModal debt terms', () => {
  describe('defaultDebtDueDate', () => {
    it('defaults to 30 days out, matching update_sale()', () => {
      expect(defaultDebtDueDate(new Date('2026-10-03T12:00:00Z'))).toBe('2026-11-02')
    })

    it('crosses a month boundary correctly', () => {
      expect(defaultDebtDueDate(new Date('2026-10-20T12:00:00Z'))).toBe('2026-11-19')
    })

    it('crosses a year boundary correctly', () => {
      expect(defaultDebtDueDate(new Date('2026-12-20T12:00:00Z'))).toBe('2027-01-19')
    })

    it('handles a leap day', () => {
      expect(defaultDebtDueDate(new Date('2028-02-01T12:00:00Z'))).toBe('2028-03-02')
    })
  })

  describe('outstandingBalance', () => {
    it('returns the shortfall when the amount paid is short', () => {
      expect(outstandingBalance(100, 40)).toBe(60)
    })

    it('returns zero when the sale is fully paid', () => {
      expect(outstandingBalance(100, 100)).toBe(0)
    })

    it('never returns a negative balance on an overpayment', () => {
      expect(outstandingBalance(100, 150)).toBe(0)
    })

    it('ignores floating point dust from currency maths', () => {
      // 0.1 + 0.2 style drift would otherwise look like a real shortfall
      expect(outstandingBalance(100, 99.99999999999999)).toBe(0)
      expect(outstandingBalance(0.3, 0)).toBe(0.3)
    })
  })
})